/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AngeboteRouteImport } from './routes/angebote'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as FavoritenRouteImport } from './routes/favoriten'
import { Route as ListeRouteImport } from './routes/liste'
import { Route as MaerkteRouteImport } from './routes/maerkte'
import { Route as PruefungRouteImport } from './routes/pruefung'
import { Route as RegionenRouteImport } from './routes/regionen'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SucheRouteImport } from './routes/suche'
import { Route as FavoritenFreundeRouteImport } from './routes/favoriten_.freunde'
import { Route as FavoritenTeilenRouteImport } from './routes/favoriten_.teilen'
import { Route as ProduktProductIdRouteImport } from './routes/produkt.$productId'
import { Route as FavoritenGeteiltTokenRouteImport } from './routes/favoriten_.geteilt.$token'
import { Route as ListeEinladungTokenRouteImport } from './routes/liste_.einladung.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AngeboteRoute = AngeboteRouteImport.update({
  id: '/angebote',
  path: '/angebote',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritenRoute = FavoritenRouteImport.update({
  id: '/favoriten',
  path: '/favoriten',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeRoute = ListeRouteImport.update({
  id: '/liste',
  path: '/liste',
  getParentRoute: () => rootRouteImport,
} as any)
const MaerkteRoute = MaerkteRouteImport.update({
  id: '/maerkte',
  path: '/maerkte',
  getParentRoute: () => rootRouteImport,
} as any)
const PruefungRoute = PruefungRouteImport.update({
  id: '/pruefung',
  path: '/pruefung',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionenRoute = RegionenRouteImport.update({
  id: '/regionen',
  path: '/regionen',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SucheRoute = SucheRouteImport.update({
  id: '/suche',
  path: '/suche',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritenFreundeRoute = FavoritenFreundeRouteImport.update({
  id: '/favoriten_/freunde',
  path: '/favoriten/freunde',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritenTeilenRoute = FavoritenTeilenRouteImport.update({
  id: '/favoriten_/teilen',
  path: '/favoriten/teilen',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktProductIdRoute = ProduktProductIdRouteImport.update({
  id: '/produkt/$productId',
  path: '/produkt/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritenGeteiltTokenRoute = FavoritenGeteiltTokenRouteImport.update({
  id: '/favoriten_/geteilt/$token',
  path: '/favoriten/geteilt/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeEinladungTokenRoute = ListeEinladungTokenRouteImport.update({
  id: '/liste_/einladung/$token',
  path: '/liste/einladung/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/auth': typeof AuthRoute
  '/einstellungen': typeof EinstellungenRoute
  '/favoriten': typeof FavoritenRoute
  '/liste': typeof ListeRoute
  '/maerkte': typeof MaerkteRoute
  '/pruefung': typeof PruefungRoute
  '/regionen': typeof RegionenRoute
  '/scanner': typeof ScannerRoute
  '/suche': typeof SucheRoute
  '/favoriten/freunde': typeof FavoritenFreundeRoute
  '/favoriten/teilen': typeof FavoritenTeilenRoute
  '/produkt/$productId': typeof ProduktProductIdRoute
  '/favoriten/geteilt/$token': typeof FavoritenGeteiltTokenRoute
  '/liste/einladung/$token': typeof ListeEinladungTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/auth': typeof AuthRoute
  '/einstellungen': typeof EinstellungenRoute
  '/favoriten': typeof FavoritenRoute
  '/liste': typeof ListeRoute
  '/maerkte': typeof MaerkteRoute
  '/pruefung': typeof PruefungRoute
  '/regionen': typeof RegionenRoute
  '/scanner': typeof ScannerRoute
  '/suche': typeof SucheRoute
  '/favoriten/freunde': typeof FavoritenFreundeRoute
  '/favoriten/teilen': typeof FavoritenTeilenRoute
  '/produkt/$productId': typeof ProduktProductIdRoute
  '/favoriten/geteilt/$token': typeof FavoritenGeteiltTokenRoute
  '/liste/einladung/$token': typeof ListeEinladungTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/auth': typeof AuthRoute
  '/einstellungen': typeof EinstellungenRoute
  '/favoriten': typeof FavoritenRoute
  '/liste': typeof ListeRoute
  '/maerkte': typeof MaerkteRoute
  '/pruefung': typeof PruefungRoute
  '/regionen': typeof RegionenRoute
  '/scanner': typeof ScannerRoute
  '/suche': typeof SucheRoute
  '/favoriten_/freunde': typeof FavoritenFreundeRoute
  '/favoriten_/teilen': typeof FavoritenTeilenRoute
  '/produkt/$productId': typeof ProduktProductIdRoute
  '/favoriten_/geteilt/$token': typeof FavoritenGeteiltTokenRoute
  '/liste_/einladung/$token': typeof ListeEinladungTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/angebote'
    | '/auth'
    | '/einstellungen'
    | '/favoriten'
    | '/liste'
    | '/maerkte'
    | '/pruefung'
    | '/regionen'
    | '/scanner'
    | '/suche'
    | '/favoriten/freunde'
    | '/favoriten/teilen'
    | '/produkt/$productId'
    | '/favoriten/geteilt/$token'
    | '/liste/einladung/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/angebote'
    | '/auth'
    | '/einstellungen'
    | '/favoriten'
    | '/liste'
    | '/maerkte'
    | '/pruefung'
    | '/regionen'
    | '/scanner'
    | '/suche'
    | '/favoriten/freunde'
    | '/favoriten/teilen'
    | '/produkt/$productId'
    | '/favoriten/geteilt/$token'
    | '/liste/einladung/$token'
  id:
    | '__root__'
    | '/'
    | '/angebote'
    | '/auth'
    | '/einstellungen'
    | '/favoriten'
    | '/liste'
    | '/maerkte'
    | '/pruefung'
    | '/regionen'
    | '/scanner'
    | '/suche'
    | '/favoriten_/freunde'
    | '/favoriten_/teilen'
    | '/produkt/$productId'
    | '/favoriten_/geteilt/$token'
    | '/liste_/einladung/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AngeboteRoute: typeof AngeboteRoute
  AuthRoute: typeof AuthRoute
  EinstellungenRoute: typeof EinstellungenRoute
  FavoritenRoute: typeof FavoritenRoute
  ListeRoute: typeof ListeRoute
  MaerkteRoute: typeof MaerkteRoute
  PruefungRoute: typeof PruefungRoute
  RegionenRoute: typeof RegionenRoute
  ScannerRoute: typeof ScannerRoute
  SucheRoute: typeof SucheRoute
  FavoritenFreundeRoute: typeof FavoritenFreundeRoute
  FavoritenTeilenRoute: typeof FavoritenTeilenRoute
  ProduktProductIdRoute: typeof ProduktProductIdRoute
  FavoritenGeteiltTokenRoute: typeof FavoritenGeteiltTokenRoute
  ListeEinladungTokenRoute: typeof ListeEinladungTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebote': {
      id: '/angebote'
      path: '/angebote'
      fullPath: '/angebote'
      preLoaderRoute: typeof AngeboteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoriten': {
      id: '/favoriten'
      path: '/favoriten'
      fullPath: '/favoriten'
      preLoaderRoute: typeof FavoritenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liste': {
      id: '/liste'
      path: '/liste'
      fullPath: '/liste'
      preLoaderRoute: typeof ListeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maerkte': {
      id: '/maerkte'
      path: '/maerkte'
      fullPath: '/maerkte'
      preLoaderRoute: typeof MaerkteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pruefung': {
      id: '/pruefung'
      path: '/pruefung'
      fullPath: '/pruefung'
      preLoaderRoute: typeof PruefungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regionen': {
      id: '/regionen'
      path: '/regionen'
      fullPath: '/regionen'
      preLoaderRoute: typeof RegionenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suche': {
      id: '/suche'
      path: '/suche'
      fullPath: '/suche'
      preLoaderRoute: typeof SucheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoriten_/freunde': {
      id: '/favoriten_/freunde'
      path: '/favoriten/freunde'
      fullPath: '/favoriten/freunde'
      preLoaderRoute: typeof FavoritenFreundeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoriten_/teilen': {
      id: '/favoriten_/teilen'
      path: '/favoriten/teilen'
      fullPath: '/favoriten/teilen'
      preLoaderRoute: typeof FavoritenTeilenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkt/$productId': {
      id: '/produkt/$productId'
      path: '/produkt/$productId'
      fullPath: '/produkt/$productId'
      preLoaderRoute: typeof ProduktProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoriten_/geteilt/$token': {
      id: '/favoriten_/geteilt/$token'
      path: '/favoriten/geteilt/$token'
      fullPath: '/favoriten/geteilt/$token'
      preLoaderRoute: typeof FavoritenGeteiltTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liste_/einladung/$token': {
      id: '/liste_/einladung/$token'
      path: '/liste/einladung/$token'
      fullPath: '/liste/einladung/$token'
      preLoaderRoute: typeof ListeEinladungTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AngeboteRoute: AngeboteRoute,
  AuthRoute: AuthRoute,
  EinstellungenRoute: EinstellungenRoute,
  FavoritenRoute: FavoritenRoute,
  ListeRoute: ListeRoute,
  MaerkteRoute: MaerkteRoute,
  PruefungRoute: PruefungRoute,
  RegionenRoute: RegionenRoute,
  ScannerRoute: ScannerRoute,
  SucheRoute: SucheRoute,
  FavoritenFreundeRoute: FavoritenFreundeRoute,
  FavoritenTeilenRoute: FavoritenTeilenRoute,
  ProduktProductIdRoute: ProduktProductIdRoute,
  FavoritenGeteiltTokenRoute: FavoritenGeteiltTokenRoute,
  ListeEinladungTokenRoute: ListeEinladungTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
