"""baseline current schema

Revision ID: 20260825_01
Revises:
Create Date: 2026-08-25 10:03:01.937432
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260825_01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_created_at'), 'admin_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_entity_id'), 'admin_audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_entity_type'), 'admin_audit_log', ['entity_type'], unique=False)
    op.create_table('admin_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('coverage_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_regions_active'), 'coverage_regions', ['active'], unique=False)
    op.create_index(op.f('ix_coverage_regions_city'), 'coverage_regions', ['city'], unique=False)
    op.create_index(op.f('ix_coverage_regions_created_at'), 'coverage_regions', ['created_at'], unique=False)
    op.create_index(op.f('ix_coverage_regions_name'), 'coverage_regions', ['name'], unique=True)
    op.create_index(op.f('ix_coverage_regions_postal_code'), 'coverage_regions', ['postal_code'], unique=False)
    op.create_index(op.f('ix_coverage_regions_status'), 'coverage_regions', ['status'], unique=False)
    op.create_table('master_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('package_size', sa.String(length=80), nullable=True),
    sa.Column('normalized_key', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_products_brand'), 'master_products', ['brand'], unique=False)
    op.create_index(op.f('ix_master_products_name'), 'master_products', ['name'], unique=False)
    op.create_index(op.f('ix_master_products_normalized_key'), 'master_products', ['normalized_key'], unique=True)
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_active'), 'product_categories', ['active'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    op.create_index(op.f('ix_product_categories_slug'), 'product_categories', ['slug'], unique=True)
    op.create_table('reviewer_device_grants',
    sa.Column('client_key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('granted_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('client_key')
    )
    op.create_index(op.f('ix_reviewer_device_grants_expires_at'), 'reviewer_device_grants', ['expires_at'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retailer', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('benchmark_verified', sa.Boolean(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_stores_benchmark_verified'), 'stores', ['benchmark_verified'], unique=False)
    op.create_index(op.f('ix_stores_city'), 'stores', ['city'], unique=False)
    op.create_index(op.f('ix_stores_external_id'), 'stores', ['external_id'], unique=False)
    op.create_index(op.f('ix_stores_postal_code'), 'stores', ['postal_code'], unique=False)
    op.create_index(op.f('ix_stores_retailer'), 'stores', ['retailer'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_subject', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_account_identity_provider_subject')
    )
    op.create_index(op.f('ix_account_identities_created_at'), 'account_identities', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_identities_email'), 'account_identities', ['email'], unique=False)
    op.create_index(op.f('ix_account_identities_last_seen_at'), 'account_identities', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_account_identities_provider'), 'account_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_account_identities_provider_subject'), 'account_identities', ['provider_subject'], unique=False)
    op.create_index(op.f('ix_account_identities_user_id'), 'account_identities', ['user_id'], unique=False)
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('offers_received', sa.Integer(), nullable=False),
    sa.Column('offers_imported', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_runs_source_key'), 'collection_runs', ['source_key'], unique=False)
    op.create_index(op.f('ix_collection_runs_started_at'), 'collection_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_collection_runs_status'), 'collection_runs', ['status'], unique=False)
    op.create_index(op.f('ix_collection_runs_store_id'), 'collection_runs', ['store_id'], unique=False)
    op.create_table('favorite_alternative_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('master_product_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'master_product_id', name='uq_favorite_alternative_preference')
    )
    op.create_index(op.f('ix_favorite_alternative_preferences_master_product_id'), 'favorite_alternative_preferences', ['master_product_id'], unique=False)
    op.create_index(op.f('ix_favorite_alternative_preferences_user_id'), 'favorite_alternative_preferences', ['user_id'], unique=False)
    op.create_table('favorite_product_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'family_slug', name='uq_favorite_product_family')
    )
    op.create_index(op.f('ix_favorite_product_families_created_at'), 'favorite_product_families', ['created_at'], unique=False)
    op.create_index(op.f('ix_favorite_product_families_family_slug'), 'favorite_product_families', ['family_slug'], unique=False)
    op.create_index(op.f('ix_favorite_product_families_user_id'), 'favorite_product_families', ['user_id'], unique=False)
    op.create_table('favorite_product_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('master_product_id', sa.Integer(), nullable=False),
    sa.Column('allow_alternatives', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'master_product_id', name='uq_favorite_product_preference')
    )
    op.create_index(op.f('ix_favorite_product_preferences_allow_alternatives'), 'favorite_product_preferences', ['allow_alternatives'], unique=False)
    op.create_index(op.f('ix_favorite_product_preferences_master_product_id'), 'favorite_product_preferences', ['master_product_id'], unique=False)
    op.create_index(op.f('ix_favorite_product_preferences_user_id'), 'favorite_product_preferences', ['user_id'], unique=False)
    op.create_table('favorite_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('master_product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'master_product_id', name='uq_favorite_product')
    )
    op.create_index(op.f('ix_favorite_products_master_product_id'), 'favorite_products', ['master_product_id'], unique=False)
    op.create_index(op.f('ix_favorite_products_user_id'), 'favorite_products', ['user_id'], unique=False)
    op.create_table('favorite_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'store_id', name='uq_favorite_store')
    )
    op.create_index(op.f('ix_favorite_stores_store_id'), 'favorite_stores', ['store_id'], unique=False)
    op.create_index(op.f('ix_favorite_stores_user_id'), 'favorite_stores', ['user_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('master_product_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('retailer', sa.String(length=80), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('alt_text', sa.String(length=240), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_active'), 'media_assets', ['active'], unique=False)
    op.create_index(op.f('ix_media_assets_is_primary'), 'media_assets', ['is_primary'], unique=False)
    op.create_index(op.f('ix_media_assets_kind'), 'media_assets', ['kind'], unique=False)
    op.create_index(op.f('ix_media_assets_master_product_id'), 'media_assets', ['master_product_id'], unique=False)
    op.create_index(op.f('ix_media_assets_retailer'), 'media_assets', ['retailer'], unique=False)
    op.create_index(op.f('ix_media_assets_store_id'), 'media_assets', ['store_id'], unique=False)
    op.create_table('normal_price_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_product_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('retailer', sa.String(length=80), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_regular_price', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_product_id', 'store_id', 'observed_at', 'price', 'source', name='uq_normal_price_observation')
    )
    op.create_index(op.f('ix_normal_price_observations_is_regular_price'), 'normal_price_observations', ['is_regular_price'], unique=False)
    op.create_index(op.f('ix_normal_price_observations_master_product_id'), 'normal_price_observations', ['master_product_id'], unique=False)
    op.create_index(op.f('ix_normal_price_observations_observed_at'), 'normal_price_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_normal_price_observations_retailer'), 'normal_price_observations', ['retailer'], unique=False)
    op.create_index(op.f('ix_normal_price_observations_source'), 'normal_price_observations', ['source'], unique=False)
    op.create_index(op.f('ix_normal_price_observations_store_id'), 'normal_price_observations', ['store_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('master_product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('unit_price_unit', sa.String(length=20), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('local_store_offer', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'master_product_id', 'valid_from', 'price', name='uq_offer')
    )
    op.create_index(op.f('ix_offers_master_product_id'), 'offers', ['master_product_id'], unique=False)
    op.create_index(op.f('ix_offers_store_id'), 'offers', ['store_id'], unique=False)
    op.create_index(op.f('ix_offers_valid_from'), 'offers', ['valid_from'], unique=False)
    op.create_index(op.f('ix_offers_valid_to'), 'offers', ['valid_to'], unique=False)
    op.create_table('product_admin_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name_locked', sa.Boolean(), nullable=False),
    sa.Column('category_locked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_product_id', name='uq_product_admin_data')
    )
    op.create_index(op.f('ix_product_admin_data_category_id'), 'product_admin_data', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_admin_data_master_product_id'), 'product_admin_data', ['master_product_id'], unique=False)
    op.create_table('product_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_key', sa.String(length=320), nullable=False),
    sa.Column('master_product_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_key', name='uq_product_alias_key')
    )
    op.create_index(op.f('ix_product_aliases_alias_key'), 'product_aliases', ['alias_key'], unique=False)
    op.create_index(op.f('ix_product_aliases_master_product_id'), 'product_aliases', ['master_product_id'], unique=False)
    op.create_table('product_barcodes',
    sa.Column('barcode', sa.String(length=14), nullable=False),
    sa.Column('master_product_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.PrimaryKeyConstraint('barcode')
    )
    op.create_index(op.f('ix_product_barcodes_master_product_id'), 'product_barcodes', ['master_product_id'], unique=False)
    op.create_table('prospect_archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('retailer', sa.String(length=80), nullable=False),
    sa.Column('period_key', sa.String(length=40), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=False),
    sa.Column('pdf_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'pdf_sha256', name='uq_store_prospect_pdf_hash')
    )
    op.create_index(op.f('ix_prospect_archives_fetched_at'), 'prospect_archives', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_prospect_archives_pdf_sha256'), 'prospect_archives', ['pdf_sha256'], unique=False)
    op.create_index(op.f('ix_prospect_archives_period_key'), 'prospect_archives', ['period_key'], unique=False)
    op.create_index(op.f('ix_prospect_archives_retailer'), 'prospect_archives', ['retailer'], unique=False)
    op.create_index(op.f('ix_prospect_archives_store_id'), 'prospect_archives', ['store_id'], unique=False)
    op.create_index(op.f('ix_prospect_archives_valid_from'), 'prospect_archives', ['valid_from'], unique=False)
    op.create_index(op.f('ix_prospect_archives_valid_to'), 'prospect_archives', ['valid_to'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('period_key', sa.String(length=40), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'period_key', name='uq_store_prospect_period')
    )
    op.create_index(op.f('ix_prospects_active'), 'prospects', ['active'], unique=False)
    op.create_index(op.f('ix_prospects_fetched_at'), 'prospects', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_prospects_period_key'), 'prospects', ['period_key'], unique=False)
    op.create_index(op.f('ix_prospects_store_id'), 'prospects', ['store_id'], unique=False)
    op.create_index(op.f('ix_prospects_valid_from'), 'prospects', ['valid_from'], unique=False)
    op.create_index(op.f('ix_prospects_valid_to'), 'prospects', ['valid_to'], unique=False)
    op.create_table('region_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('postal_code', 'email', 'user_id', name='uq_region_interest')
    )
    op.create_index(op.f('ix_region_interests_created_at'), 'region_interests', ['created_at'], unique=False)
    op.create_index(op.f('ix_region_interests_email'), 'region_interests', ['email'], unique=False)
    op.create_index(op.f('ix_region_interests_postal_code'), 'region_interests', ['postal_code'], unique=False)
    op.create_index(op.f('ix_region_interests_user_id'), 'region_interests', ['user_id'], unique=False)
    op.create_table('shopping_item_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('master_product_id', sa.Integer(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'master_product_id', name='uq_shopping_item_check')
    )
    op.create_index(op.f('ix_shopping_item_checks_master_product_id'), 'shopping_item_checks', ['master_product_id'], unique=False)
    op.create_index(op.f('ix_shopping_item_checks_user_id'), 'shopping_item_checks', ['user_id'], unique=False)
    op.create_table('shopping_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('master_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'master_product_id', name='uq_shopping_item')
    )
    op.create_index(op.f('ix_shopping_items_master_product_id'), 'shopping_items', ['master_product_id'], unique=False)
    op.create_index(op.f('ix_shopping_items_user_id'), 'shopping_items', ['user_id'], unique=False)
    op.create_table('user_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_key', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('pwa_installed', sa.Boolean(), nullable=False),
    sa.Column('pwa_last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.String(length=80), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_clients_client_key'), 'user_clients', ['client_key'], unique=True)
    op.create_index(op.f('ix_user_clients_first_seen_at'), 'user_clients', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_user_clients_last_seen_at'), 'user_clients', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_user_clients_pwa_installed'), 'user_clients', ['pwa_installed'], unique=False)
    op.create_index(op.f('ix_user_clients_pwa_last_seen_at'), 'user_clients', ['pwa_last_seen_at'], unique=False)
    op.create_index(op.f('ix_user_clients_user_id'), 'user_clients', ['user_id'], unique=True)
    op.create_table('account_client_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user_clients.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['account_identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', name='uq_account_client_link_client'),
    sa.UniqueConstraint('identity_id', 'client_id', name='uq_account_client_identity_client')
    )
    op.create_index(op.f('ix_account_client_links_client_id'), 'account_client_links', ['client_id'], unique=False)
    op.create_index(op.f('ix_account_client_links_identity_id'), 'account_client_links', ['identity_id'], unique=False)
    op.create_index(op.f('ix_account_client_links_last_seen_at'), 'account_client_links', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_account_client_links_linked_at'), 'account_client_links', ['linked_at'], unique=False)
    op.create_table('client_activity_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('home_views', sa.Integer(), nullable=False),
    sa.Column('offers_views', sa.Integer(), nullable=False),
    sa.Column('favorites_views', sa.Integer(), nullable=False),
    sa.Column('shopping_views', sa.Integer(), nullable=False),
    sa.Column('stores_views', sa.Integer(), nullable=False),
    sa.Column('settings_views', sa.Integer(), nullable=False),
    sa.Column('store_detail_views', sa.Integer(), nullable=False),
    sa.Column('other_views', sa.Integer(), nullable=False),
    sa.Column('favorite_products_count', sa.Integer(), nullable=False),
    sa.Column('favorite_stores_count', sa.Integer(), nullable=False),
    sa.Column('shopping_items_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user_clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'activity_date', name='uq_client_activity_day')
    )
    op.create_index(op.f('ix_client_activity_days_activity_date'), 'client_activity_days', ['activity_date'], unique=False)
    op.create_index(op.f('ix_client_activity_days_client_id'), 'client_activity_days', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_activity_days_last_seen_at'), 'client_activity_days', ['last_seen_at'], unique=False)
    op.create_table('client_app_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user_clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_app_ratings_client_id'), 'client_app_ratings', ['client_id'], unique=True)
    op.create_index(op.f('ix_client_app_ratings_rating'), 'client_app_ratings', ['rating'], unique=False)
    op.create_index(op.f('ix_client_app_ratings_submitted_at'), 'client_app_ratings', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_client_app_ratings_user_id'), 'client_app_ratings', ['user_id'], unique=False)
    op.create_table('client_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('device_key', sa.String(length=80), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('os_name', sa.String(length=40), nullable=False),
    sa.Column('os_version', sa.String(length=40), nullable=True),
    sa.Column('browser_name', sa.String(length=40), nullable=False),
    sa.Column('browser_version', sa.String(length=40), nullable=True),
    sa.Column('platform', sa.String(length=80), nullable=True),
    sa.Column('mobile_hint', sa.Boolean(), nullable=False),
    sa.Column('touch_points', sa.Integer(), nullable=False),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('pixel_ratio', sa.Float(), nullable=True),
    sa.Column('standalone', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_devices_browser_name'), 'client_devices', ['browser_name'], unique=False)
    op.create_index(op.f('ix_client_devices_client_id'), 'client_devices', ['client_id'], unique=True)
    op.create_index(op.f('ix_client_devices_device_key'), 'client_devices', ['device_key'], unique=True)
    op.create_index(op.f('ix_client_devices_device_type'), 'client_devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_client_devices_first_seen_at'), 'client_devices', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_client_devices_last_seen_at'), 'client_devices', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_client_devices_mobile_hint'), 'client_devices', ['mobile_hint'], unique=False)
    op.create_index(op.f('ix_client_devices_os_name'), 'client_devices', ['os_name'], unique=False)
    op.create_index(op.f('ix_client_devices_standalone'), 'client_devices', ['standalone'], unique=False)
    op.create_table('client_feature_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('first_used_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user_clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'feature', name='uq_client_feature_usage')
    )
    op.create_index(op.f('ix_client_feature_usage_client_id'), 'client_feature_usage', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_feature_usage_feature'), 'client_feature_usage', ['feature'], unique=False)
    op.create_index(op.f('ix_client_feature_usage_last_used_at'), 'client_feature_usage', ['last_used_at'], unique=False)
    op.create_table('client_pricing_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('savings_value', sa.String(length=24), nullable=False),
    sa.Column('monthly_price', sa.String(length=12), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user_clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_pricing_feedback_client_id'), 'client_pricing_feedback', ['client_id'], unique=True)
    op.create_index(op.f('ix_client_pricing_feedback_monthly_price'), 'client_pricing_feedback', ['monthly_price'], unique=False)
    op.create_index(op.f('ix_client_pricing_feedback_savings_value'), 'client_pricing_feedback', ['savings_value'], unique=False)
    op.create_index(op.f('ix_client_pricing_feedback_submitted_at'), 'client_pricing_feedback', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_client_pricing_feedback_user_id'), 'client_pricing_feedback', ['user_id'], unique=False)
    op.create_table('client_usage_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('entry_page', sa.String(length=30), nullable=True),
    sa.Column('last_page', sa.String(length=30), nullable=True),
    sa.Column('pwa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_usage_sessions_client_id'), 'client_usage_sessions', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_usage_sessions_last_seen_at'), 'client_usage_sessions', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_client_usage_sessions_pwa'), 'client_usage_sessions', ['pwa'], unique=False)
    op.create_index(op.f('ix_client_usage_sessions_started_at'), 'client_usage_sessions', ['started_at'], unique=False)
    op.create_table('collection_quality_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('retailer', sa.String(length=80), nullable=False),
    sa.Column('run_status', sa.String(length=30), nullable=False),
    sa.Column('quality_status', sa.String(length=20), nullable=False),
    sa.Column('benchmark_status', sa.String(length=20), nullable=False),
    sa.Column('benchmark_context', sa.String(length=20), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['collection_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_collection_quality_run')
    )
    op.create_index(op.f('ix_collection_quality_snapshots_benchmark_context'), 'collection_quality_snapshots', ['benchmark_context'], unique=False)
    op.create_index(op.f('ix_collection_quality_snapshots_benchmark_status'), 'collection_quality_snapshots', ['benchmark_status'], unique=False)
    op.create_index(op.f('ix_collection_quality_snapshots_created_at'), 'collection_quality_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_collection_quality_snapshots_quality_status'), 'collection_quality_snapshots', ['quality_status'], unique=False)
    op.create_index(op.f('ix_collection_quality_snapshots_retailer'), 'collection_quality_snapshots', ['retailer'], unique=False)
    op.create_index(op.f('ix_collection_quality_snapshots_run_id'), 'collection_quality_snapshots', ['run_id'], unique=False)
    op.create_index(op.f('ix_collection_quality_snapshots_run_status'), 'collection_quality_snapshots', ['run_status'], unique=False)
    op.create_index(op.f('ix_collection_quality_snapshots_store_id'), 'collection_quality_snapshots', ['store_id'], unique=False)
    op.create_table('collection_run_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('pages_total', sa.Integer(), nullable=True),
    sa.Column('pages_structured', sa.Integer(), nullable=False),
    sa.Column('pages_ocr', sa.Integer(), nullable=False),
    sa.Column('pages_done', sa.Integer(), nullable=False),
    sa.Column('assets_cached', sa.Integer(), nullable=False),
    sa.Column('elapsed_seconds', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['collection_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_collection_run_progress_run')
    )
    op.create_index(op.f('ix_collection_run_progress_phase'), 'collection_run_progress', ['phase'], unique=False)
    op.create_index(op.f('ix_collection_run_progress_run_id'), 'collection_run_progress', ['run_id'], unique=False)
    op.create_table('media_asset_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('media_source', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('audit_relevant', sa.Boolean(), nullable=False),
    sa.Column('external_product_id', sa.String(length=160), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_asset_id', name='uq_media_asset_metadata_asset')
    )
    op.create_index(op.f('ix_media_asset_metadata_audit_relevant'), 'media_asset_metadata', ['audit_relevant'], unique=False)
    op.create_index(op.f('ix_media_asset_metadata_external_product_id'), 'media_asset_metadata', ['external_product_id'], unique=False)
    op.create_index(op.f('ix_media_asset_metadata_media_asset_id'), 'media_asset_metadata', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_media_asset_metadata_media_source'), 'media_asset_metadata', ['media_source'], unique=False)
    op.create_index(op.f('ix_media_asset_metadata_priority'), 'media_asset_metadata', ['priority'], unique=False)
    op.create_table('offer_occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('prospect_page', sa.Integer(), nullable=True),
    sa.Column('occurrence_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('detail_text', sa.Text(), nullable=True),
    sa.Column('package_size', sa.String(length=80), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('unit_price_unit', sa.String(length=20), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id', 'occurrence_fingerprint', name='uq_offer_occurrence')
    )
    op.create_index(op.f('ix_offer_occurrences_collected_at'), 'offer_occurrences', ['collected_at'], unique=False)
    op.create_index(op.f('ix_offer_occurrences_occurrence_fingerprint'), 'offer_occurrences', ['occurrence_fingerprint'], unique=False)
    op.create_index(op.f('ix_offer_occurrences_offer_id'), 'offer_occurrences', ['offer_id'], unique=False)
    op.create_index(op.f('ix_offer_occurrences_prospect_page'), 'offer_occurrences', ['prospect_page'], unique=False)
    op.create_table('offer_price_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('reference_price', sa.Float(), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id', name='uq_offer_price_reference')
    )
    op.create_index(op.f('ix_offer_price_references_offer_id'), 'offer_price_references', ['offer_id'], unique=False)
    op.create_table('offer_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('prospect_archive_id', sa.Integer(), nullable=False),
    sa.Column('prospect_page', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['prospect_archive_id'], ['prospect_archives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id', 'prospect_archive_id', 'prospect_page', name='uq_offer_prospect_page')
    )
    op.create_index(op.f('ix_offer_provenance_collected_at'), 'offer_provenance', ['collected_at'], unique=False)
    op.create_index(op.f('ix_offer_provenance_offer_id'), 'offer_provenance', ['offer_id'], unique=False)
    op.create_index(op.f('ix_offer_provenance_prospect_archive_id'), 'offer_provenance', ['prospect_archive_id'], unique=False)
    op.create_index(op.f('ix_offer_provenance_prospect_page'), 'offer_provenance', ['prospect_page'], unique=False)
    op.create_table('prospect_missing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_archive_id', sa.Integer(), nullable=False),
    sa.Column('prospect_page', sa.Integer(), nullable=False),
    sa.Column('expected_name', sa.String(length=240), nullable=False),
    sa.Column('expected_brand', sa.String(length=160), nullable=True),
    sa.Column('expected_package_size', sa.String(length=120), nullable=True),
    sa.Column('expected_price', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('reported_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_archive_id'], ['prospect_archives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospect_missing_items_created_at'), 'prospect_missing_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_prospect_missing_items_prospect_archive_id'), 'prospect_missing_items', ['prospect_archive_id'], unique=False)
    op.create_index(op.f('ix_prospect_missing_items_prospect_page'), 'prospect_missing_items', ['prospect_page'], unique=False)
    op.create_index(op.f('ix_prospect_missing_items_resolved'), 'prospect_missing_items', ['resolved'], unique=False)
    op.create_table('prospect_offer_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_provenance_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('issue_type', sa.String(length=80), nullable=True),
    sa.Column('expected_name', sa.String(length=240), nullable=True),
    sa.Column('expected_brand', sa.String(length=160), nullable=True),
    sa.Column('expected_package_size', sa.String(length=120), nullable=True),
    sa.Column('expected_price', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offer_provenance_id'], ['offer_provenance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_provenance_id', name='uq_prospect_offer_review_provenance')
    )
    op.create_index(op.f('ix_prospect_offer_reviews_issue_type'), 'prospect_offer_reviews', ['issue_type'], unique=False)
    op.create_index(op.f('ix_prospect_offer_reviews_offer_provenance_id'), 'prospect_offer_reviews', ['offer_provenance_id'], unique=False)
    op.create_index(op.f('ix_prospect_offer_reviews_reviewed_at'), 'prospect_offer_reviews', ['reviewed_at'], unique=False)
    op.create_index(op.f('ix_prospect_offer_reviews_status'), 'prospect_offer_reviews', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prospect_offer_reviews_status'), table_name='prospect_offer_reviews')
    op.drop_index(op.f('ix_prospect_offer_reviews_reviewed_at'), table_name='prospect_offer_reviews')
    op.drop_index(op.f('ix_prospect_offer_reviews_offer_provenance_id'), table_name='prospect_offer_reviews')
    op.drop_index(op.f('ix_prospect_offer_reviews_issue_type'), table_name='prospect_offer_reviews')
    op.drop_table('prospect_offer_reviews')
    op.drop_index(op.f('ix_prospect_missing_items_resolved'), table_name='prospect_missing_items')
    op.drop_index(op.f('ix_prospect_missing_items_prospect_page'), table_name='prospect_missing_items')
    op.drop_index(op.f('ix_prospect_missing_items_prospect_archive_id'), table_name='prospect_missing_items')
    op.drop_index(op.f('ix_prospect_missing_items_created_at'), table_name='prospect_missing_items')
    op.drop_table('prospect_missing_items')
    op.drop_index(op.f('ix_offer_provenance_prospect_page'), table_name='offer_provenance')
    op.drop_index(op.f('ix_offer_provenance_prospect_archive_id'), table_name='offer_provenance')
    op.drop_index(op.f('ix_offer_provenance_offer_id'), table_name='offer_provenance')
    op.drop_index(op.f('ix_offer_provenance_collected_at'), table_name='offer_provenance')
    op.drop_table('offer_provenance')
    op.drop_index(op.f('ix_offer_price_references_offer_id'), table_name='offer_price_references')
    op.drop_table('offer_price_references')
    op.drop_index(op.f('ix_offer_occurrences_prospect_page'), table_name='offer_occurrences')
    op.drop_index(op.f('ix_offer_occurrences_offer_id'), table_name='offer_occurrences')
    op.drop_index(op.f('ix_offer_occurrences_occurrence_fingerprint'), table_name='offer_occurrences')
    op.drop_index(op.f('ix_offer_occurrences_collected_at'), table_name='offer_occurrences')
    op.drop_table('offer_occurrences')
    op.drop_index(op.f('ix_media_asset_metadata_priority'), table_name='media_asset_metadata')
    op.drop_index(op.f('ix_media_asset_metadata_media_source'), table_name='media_asset_metadata')
    op.drop_index(op.f('ix_media_asset_metadata_media_asset_id'), table_name='media_asset_metadata')
    op.drop_index(op.f('ix_media_asset_metadata_external_product_id'), table_name='media_asset_metadata')
    op.drop_index(op.f('ix_media_asset_metadata_audit_relevant'), table_name='media_asset_metadata')
    op.drop_table('media_asset_metadata')
    op.drop_index(op.f('ix_collection_run_progress_run_id'), table_name='collection_run_progress')
    op.drop_index(op.f('ix_collection_run_progress_phase'), table_name='collection_run_progress')
    op.drop_table('collection_run_progress')
    op.drop_index(op.f('ix_collection_quality_snapshots_store_id'), table_name='collection_quality_snapshots')
    op.drop_index(op.f('ix_collection_quality_snapshots_run_status'), table_name='collection_quality_snapshots')
    op.drop_index(op.f('ix_collection_quality_snapshots_run_id'), table_name='collection_quality_snapshots')
    op.drop_index(op.f('ix_collection_quality_snapshots_retailer'), table_name='collection_quality_snapshots')
    op.drop_index(op.f('ix_collection_quality_snapshots_quality_status'), table_name='collection_quality_snapshots')
    op.drop_index(op.f('ix_collection_quality_snapshots_created_at'), table_name='collection_quality_snapshots')
    op.drop_index(op.f('ix_collection_quality_snapshots_benchmark_status'), table_name='collection_quality_snapshots')
    op.drop_index(op.f('ix_collection_quality_snapshots_benchmark_context'), table_name='collection_quality_snapshots')
    op.drop_table('collection_quality_snapshots')
    op.drop_index(op.f('ix_client_usage_sessions_started_at'), table_name='client_usage_sessions')
    op.drop_index(op.f('ix_client_usage_sessions_pwa'), table_name='client_usage_sessions')
    op.drop_index(op.f('ix_client_usage_sessions_last_seen_at'), table_name='client_usage_sessions')
    op.drop_index(op.f('ix_client_usage_sessions_client_id'), table_name='client_usage_sessions')
    op.drop_table('client_usage_sessions')
    op.drop_index(op.f('ix_client_pricing_feedback_user_id'), table_name='client_pricing_feedback')
    op.drop_index(op.f('ix_client_pricing_feedback_submitted_at'), table_name='client_pricing_feedback')
    op.drop_index(op.f('ix_client_pricing_feedback_savings_value'), table_name='client_pricing_feedback')
    op.drop_index(op.f('ix_client_pricing_feedback_monthly_price'), table_name='client_pricing_feedback')
    op.drop_index(op.f('ix_client_pricing_feedback_client_id'), table_name='client_pricing_feedback')
    op.drop_table('client_pricing_feedback')
    op.drop_index(op.f('ix_client_feature_usage_last_used_at'), table_name='client_feature_usage')
    op.drop_index(op.f('ix_client_feature_usage_feature'), table_name='client_feature_usage')
    op.drop_index(op.f('ix_client_feature_usage_client_id'), table_name='client_feature_usage')
    op.drop_table('client_feature_usage')
    op.drop_index(op.f('ix_client_devices_standalone'), table_name='client_devices')
    op.drop_index(op.f('ix_client_devices_os_name'), table_name='client_devices')
    op.drop_index(op.f('ix_client_devices_mobile_hint'), table_name='client_devices')
    op.drop_index(op.f('ix_client_devices_last_seen_at'), table_name='client_devices')
    op.drop_index(op.f('ix_client_devices_first_seen_at'), table_name='client_devices')
    op.drop_index(op.f('ix_client_devices_device_type'), table_name='client_devices')
    op.drop_index(op.f('ix_client_devices_device_key'), table_name='client_devices')
    op.drop_index(op.f('ix_client_devices_client_id'), table_name='client_devices')
    op.drop_index(op.f('ix_client_devices_browser_name'), table_name='client_devices')
    op.drop_table('client_devices')
    op.drop_index(op.f('ix_client_app_ratings_user_id'), table_name='client_app_ratings')
    op.drop_index(op.f('ix_client_app_ratings_submitted_at'), table_name='client_app_ratings')
    op.drop_index(op.f('ix_client_app_ratings_rating'), table_name='client_app_ratings')
    op.drop_index(op.f('ix_client_app_ratings_client_id'), table_name='client_app_ratings')
    op.drop_table('client_app_ratings')
    op.drop_index(op.f('ix_client_activity_days_last_seen_at'), table_name='client_activity_days')
    op.drop_index(op.f('ix_client_activity_days_client_id'), table_name='client_activity_days')
    op.drop_index(op.f('ix_client_activity_days_activity_date'), table_name='client_activity_days')
    op.drop_table('client_activity_days')
    op.drop_index(op.f('ix_account_client_links_linked_at'), table_name='account_client_links')
    op.drop_index(op.f('ix_account_client_links_last_seen_at'), table_name='account_client_links')
    op.drop_index(op.f('ix_account_client_links_identity_id'), table_name='account_client_links')
    op.drop_index(op.f('ix_account_client_links_client_id'), table_name='account_client_links')
    op.drop_table('account_client_links')
    op.drop_index(op.f('ix_user_clients_user_id'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_pwa_last_seen_at'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_pwa_installed'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_last_seen_at'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_first_seen_at'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_client_key'), table_name='user_clients')
    op.drop_table('user_clients')
    op.drop_index(op.f('ix_shopping_items_user_id'), table_name='shopping_items')
    op.drop_index(op.f('ix_shopping_items_master_product_id'), table_name='shopping_items')
    op.drop_table('shopping_items')
    op.drop_index(op.f('ix_shopping_item_checks_user_id'), table_name='shopping_item_checks')
    op.drop_index(op.f('ix_shopping_item_checks_master_product_id'), table_name='shopping_item_checks')
    op.drop_table('shopping_item_checks')
    op.drop_index(op.f('ix_region_interests_user_id'), table_name='region_interests')
    op.drop_index(op.f('ix_region_interests_postal_code'), table_name='region_interests')
    op.drop_index(op.f('ix_region_interests_email'), table_name='region_interests')
    op.drop_index(op.f('ix_region_interests_created_at'), table_name='region_interests')
    op.drop_table('region_interests')
    op.drop_index(op.f('ix_prospects_valid_to'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_valid_from'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_store_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_period_key'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_fetched_at'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_active'), table_name='prospects')
    op.drop_table('prospects')
    op.drop_index(op.f('ix_prospect_archives_valid_to'), table_name='prospect_archives')
    op.drop_index(op.f('ix_prospect_archives_valid_from'), table_name='prospect_archives')
    op.drop_index(op.f('ix_prospect_archives_store_id'), table_name='prospect_archives')
    op.drop_index(op.f('ix_prospect_archives_retailer'), table_name='prospect_archives')
    op.drop_index(op.f('ix_prospect_archives_period_key'), table_name='prospect_archives')
    op.drop_index(op.f('ix_prospect_archives_pdf_sha256'), table_name='prospect_archives')
    op.drop_index(op.f('ix_prospect_archives_fetched_at'), table_name='prospect_archives')
    op.drop_table('prospect_archives')
    op.drop_index(op.f('ix_product_barcodes_master_product_id'), table_name='product_barcodes')
    op.drop_table('product_barcodes')
    op.drop_index(op.f('ix_product_aliases_master_product_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_alias_key'), table_name='product_aliases')
    op.drop_table('product_aliases')
    op.drop_index(op.f('ix_product_admin_data_master_product_id'), table_name='product_admin_data')
    op.drop_index(op.f('ix_product_admin_data_category_id'), table_name='product_admin_data')
    op.drop_table('product_admin_data')
    op.drop_index(op.f('ix_offers_valid_to'), table_name='offers')
    op.drop_index(op.f('ix_offers_valid_from'), table_name='offers')
    op.drop_index(op.f('ix_offers_store_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_master_product_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_normal_price_observations_store_id'), table_name='normal_price_observations')
    op.drop_index(op.f('ix_normal_price_observations_source'), table_name='normal_price_observations')
    op.drop_index(op.f('ix_normal_price_observations_retailer'), table_name='normal_price_observations')
    op.drop_index(op.f('ix_normal_price_observations_observed_at'), table_name='normal_price_observations')
    op.drop_index(op.f('ix_normal_price_observations_master_product_id'), table_name='normal_price_observations')
    op.drop_index(op.f('ix_normal_price_observations_is_regular_price'), table_name='normal_price_observations')
    op.drop_table('normal_price_observations')
    op.drop_index(op.f('ix_media_assets_store_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_retailer'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_master_product_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_kind'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_is_primary'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_active'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_favorite_stores_user_id'), table_name='favorite_stores')
    op.drop_index(op.f('ix_favorite_stores_store_id'), table_name='favorite_stores')
    op.drop_table('favorite_stores')
    op.drop_index(op.f('ix_favorite_products_user_id'), table_name='favorite_products')
    op.drop_index(op.f('ix_favorite_products_master_product_id'), table_name='favorite_products')
    op.drop_table('favorite_products')
    op.drop_index(op.f('ix_favorite_product_preferences_user_id'), table_name='favorite_product_preferences')
    op.drop_index(op.f('ix_favorite_product_preferences_master_product_id'), table_name='favorite_product_preferences')
    op.drop_index(op.f('ix_favorite_product_preferences_allow_alternatives'), table_name='favorite_product_preferences')
    op.drop_table('favorite_product_preferences')
    op.drop_index(op.f('ix_favorite_product_families_user_id'), table_name='favorite_product_families')
    op.drop_index(op.f('ix_favorite_product_families_family_slug'), table_name='favorite_product_families')
    op.drop_index(op.f('ix_favorite_product_families_created_at'), table_name='favorite_product_families')
    op.drop_table('favorite_product_families')
    op.drop_index(op.f('ix_favorite_alternative_preferences_user_id'), table_name='favorite_alternative_preferences')
    op.drop_index(op.f('ix_favorite_alternative_preferences_master_product_id'), table_name='favorite_alternative_preferences')
    op.drop_table('favorite_alternative_preferences')
    op.drop_index(op.f('ix_collection_runs_store_id'), table_name='collection_runs')
    op.drop_index(op.f('ix_collection_runs_status'), table_name='collection_runs')
    op.drop_index(op.f('ix_collection_runs_started_at'), table_name='collection_runs')
    op.drop_index(op.f('ix_collection_runs_source_key'), table_name='collection_runs')
    op.drop_table('collection_runs')
    op.drop_index(op.f('ix_account_identities_user_id'), table_name='account_identities')
    op.drop_index(op.f('ix_account_identities_provider_subject'), table_name='account_identities')
    op.drop_index(op.f('ix_account_identities_provider'), table_name='account_identities')
    op.drop_index(op.f('ix_account_identities_last_seen_at'), table_name='account_identities')
    op.drop_index(op.f('ix_account_identities_email'), table_name='account_identities')
    op.drop_index(op.f('ix_account_identities_created_at'), table_name='account_identities')
    op.drop_table('account_identities')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_stores_retailer'), table_name='stores')
    op.drop_index(op.f('ix_stores_postal_code'), table_name='stores')
    op.drop_index(op.f('ix_stores_external_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_city'), table_name='stores')
    op.drop_index(op.f('ix_stores_benchmark_verified'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_reviewer_device_grants_expires_at'), table_name='reviewer_device_grants')
    op.drop_table('reviewer_device_grants')
    op.drop_index(op.f('ix_product_categories_slug'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_active'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_master_products_normalized_key'), table_name='master_products')
    op.drop_index(op.f('ix_master_products_name'), table_name='master_products')
    op.drop_index(op.f('ix_master_products_brand'), table_name='master_products')
    op.drop_table('master_products')
    op.drop_index(op.f('ix_coverage_regions_status'), table_name='coverage_regions')
    op.drop_index(op.f('ix_coverage_regions_postal_code'), table_name='coverage_regions')
    op.drop_index(op.f('ix_coverage_regions_name'), table_name='coverage_regions')
    op.drop_index(op.f('ix_coverage_regions_created_at'), table_name='coverage_regions')
    op.drop_index(op.f('ix_coverage_regions_city'), table_name='coverage_regions')
    op.drop_index(op.f('ix_coverage_regions_active'), table_name='coverage_regions')
    op.drop_table('coverage_regions')
    op.drop_table('admin_settings')
    op.drop_index(op.f('ix_admin_audit_log_entity_type'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_entity_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_created_at'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
